## Matrix vector multiplication
### Problem Set 1 - Task 2.12

In [1]:
import numpy as np

In [2]:
# matrix A (3x3)
A = np.array([[1, 3, 4], [2, 1, 3], [3, -1, 1]])

In [3]:
print(A)

[[ 1  3  4]
 [ 2  1  3]
 [ 3 -1  1]]


In [4]:
# vektor x 
x = np.array([1,2,3])

In [5]:
print(x)

[1 2 3]


In [6]:
# Solution of Ax = 
b = A.dot(x)

In [7]:
print(b)

[19 13  4]
